name: network_dio_native
description: Network dio native implementation
version: 1.0.0 
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  network_dio:
    # git:
    #   url: git@github.com:rasyadh/network_dio.git
    #   path: impl/network_dio
    path: ../network_dio

  native_dio_adapter: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^0.2.0

dependency_overrides:
  network_dio:
    path: ../network_dio
