name: network_dio
description: Network implementation with Dio
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  dio_http2_adapter: ^2.0.0
  http_parser: ^4.0.0

  network:
    path: ../../.
    # git:
    #   url: git@github.com:rasyadh/network.git
  json_converter:
    git:
      url: git@github.com:rasyadh/json_converter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http_mock_adapter: ^0.6.1
  mocktail: ^0.2.0
  faker: ^2.0.0
